name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to upload to'
        default: ''

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        target_cpu:
          - x86-64
          - haswell
          - skylake
          - alderlake
          - raptorlake
          - arrowlake
          - znver2
          - znver3
          - znver4
          - znver5
        toolchain:
          - clang
          #- ucrt
    steps:
    - name: Checkout x264
      uses: actions/checkout@v4
      with:
        path: x264
        fetch-depth: 0

    - name: Cache FFmpeg
      id: cache-ff
      uses: actions/cache@v4
      with:
        path: ffmpeg
        key: ffmpeg-n8.1-minimal-v1-${{matrix.toolchain}}

    - name: Checkout FFmpeg
      uses: actions/checkout@v4
      with:
        path: ffmpeg
        repository: FFmpeg/FFmpeg
        ref: n8.1
      if: steps.cache-ff.outputs.cache-hit != 'true'

    - name: Checkout mimalloc
      uses: actions/checkout@v4
      with:
        path: mimalloc
        repository: microsoft/mimalloc
        ref: v3.2.8

    - name: Checkout obuparse
      uses: actions/checkout@v4
      with:
        path: obuparse
        repository: dwbuiten/obuparse

    - name: Checkout L-SMASH
      uses: actions/checkout@v4
      with:
        path: lsmash
        repository: vimeo/l-smash

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.toolchain == 'clang' && 'CLANG64' || 'UCRT64' }}
        update: true
        install: >-
          p7zip
          base-devel
          git
          autoconf
          automake
          libtool
          mingw-w64-${{matrix.toolchain}}-x86_64-nasm
          mingw-w64-${{matrix.toolchain}}-x86_64-toolchain
          mingw-w64-${{matrix.toolchain}}-x86_64-cmake
          mingw-w64-${{matrix.toolchain}}-x86_64-ninja

    - name: Compile FFmpeg (minimal)
      run: |
        ./configure --prefix=/usr/local --enable-gpl --enable-version3 \
          --disable-runtime-cpudetect --disable-all --disable-autodetect \
          --enable-avformat --enable-avcodec --enable-swscale --enable-swresample \
          --disable-everything --disable-network \
          --enable-demuxer=mpegts,mov,matroska,h264,hevc,rawvideo,yuv4mpegpipe \
          --enable-decoder=h264,hevc,ffv1,ffvhuff,huffyuv,rawvideo,wrapped_avframe,aac,ac3,mp3 \
          --enable-protocol=file \
          --cc=cc --cxx=c++ --cpu=x86-64
        make -j$(nproc)
      working-directory: ffmpeg
      if: steps.cache-ff.outputs.cache-hit != 'true'

    - name: Get rid of .dll.a
      run: find /*64/ /usr/ -type f -name "*.dll.a" -print -delete

    - name: Install FFmpeg
      run: make install
      working-directory: ffmpeg

    - name: Checkout ffms2
      uses: actions/checkout@v4
      with:
        path: ffms2
        repository: FFMS/ffms2

    - name: Compile ffms2 (static)
      run: |
        export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
        ./autogen.sh
        ./configure --prefix=/usr/local --enable-static --disable-shared
        make -j$(nproc)
      working-directory: ffms2

    - name: Install ffms2
      run: make install
      working-directory: ffms2

    - name: Compile mimalloc
      run: |
        mkdir build
        cd build
        cmake -GNinja .. -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
          -DMI_BUILD_SHARED=OFF -DMI_BUILD_STATIC=ON -DMI_BUILD_OBJECT=OFF -DMI_BUILD_TESTS=OFF -DMI_USE_CXX=ON
        ninja
      working-directory: mimalloc

    - name: Install mimalloc
      run: ninja install
      working-directory: mimalloc/build

    - name: Compile obuparse
      run: make CC=cc libobuparse.a
      working-directory: obuparse

    - name: Install obuparse
      run: |
        install -d /usr/local/include
        install -d /usr/local/lib
        install -v obuparse.h /usr/local/include
        install -v libobuparse.a /usr/local/lib
      working-directory: obuparse

    - name: Compile L-SMASH
      run: |
        ./configure --prefix=/usr/local --cc=cc --extra-cflags="-I/usr/local/include" \
          --extra-ldflags="-L/usr/local/lib" --extra-libs="-lobuparse"
        make -j$(nproc)
      working-directory: lsmash

    - name: Install L-SMASH
      run: |
        make install
        cp importer/importer.h /usr/local/include/lsmash_importer.h
      working-directory: lsmash

    - name: Setup build dir
      run: mkdir -p build/8b build/10b build/all

    - name: Compile x264 8bit
      run: |
        export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/clang64/lib/pkgconfig
        export X264_TARGET_CPU=${{matrix.target_cpu}}
        CC=cc ../../x264/configure --prefix=/usr/local --bit-depth=8 --enable-lto --enable-lavf --enable-lsmash --enable-static \
          --extra-cflags="-O3 -I/usr/local/include -I/clang64/include -I../../ffmpeg" \
          --extra-ldflags="-L/usr/local/lib -L/clang64/lib"
        make -j$(nproc)
        strip -s x264.exe
      working-directory: build/8b

    - name: Compile x264 10bit
      run: |
        export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/clang64/lib/pkgconfig
        export X264_TARGET_CPU=${{matrix.target_cpu}}
        CC=cc ../../x264/configure --prefix=/usr/local --bit-depth=10 --enable-lto --enable-lavf --enable-lsmash --enable-static \
          --extra-cflags="-O3 -I/usr/local/include -I/clang64/include -I../../ffmpeg" \
          --extra-ldflags="-L/usr/local/lib -L/clang64/lib"
        make -j$(nproc)
        strip -s x264.exe
      working-directory: build/10b

    - name: Compile x264 8bit+10bit (all)
      run: |
        export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/clang64/lib/pkgconfig
        export X264_TARGET_CPU=${{matrix.target_cpu}}
        CC=cc ../../x264/configure --prefix=/usr/local --bit-depth=all --enable-lto --enable-lavf --enable-lsmash --enable-static \
          --extra-cflags="-O3 -I/usr/local/include -I/clang64/include -I../../ffmpeg" \
          --extra-ldflags="-L/usr/local/lib -L/clang64/lib"
        make -j$(nproc)
        strip -s x264.exe
      working-directory: build/all

    - name: Package
      run: |
        mkdir dist
        cp build/8b/x264.exe dist/x264-8bit.exe
        cp build/10b/x264.exe dist/x264-10bit.exe
        cp build/all/x264.exe dist/x264.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: x264-win64-${{matrix.target_cpu}}-${{matrix.toolchain}}
        path: dist/*

    - name: Compress artifact for release
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      run: |
        cd dist
        7za a -t7z -mx=7 ../x264-win64-${{matrix.target_cpu}}-${{matrix.toolchain}}.${{ github.event.inputs.tag }}.7z \
          x264-8bit.exe x264-10bit.exe x264.exe

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: x264-win64-${{matrix.target_cpu}}-${{matrix.toolchain}}.${{ github.event.inputs.tag }}.7z
        fail_on_unmatched_files: true
        generate_release_notes: false
        prerelease: true
